version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=db_test
      - MYSQL_ROOT_PASSWORD=pass

